### PR TITLE
Wording fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
First small fixes for the Calendar. :) Please review @libasys @DeepDiver1975 @sahne123 @MorrisJobke @schiesbn @lukasreschke

@libasys you really need to fix your whitespace … tabs and spaces are mixed all over the place. Please _only_ use tabs as per ownCloud coding guidelines.

### CODE REVIEW

**Comment by jancborchardt** [comment]
View this without the whitespace changes: https://github.com/libasys/calendarplus/pull/55/files?w=1

**Comment by MorrisJobke** [comment]
:+1:

**Comment by schiessle** [comment]
looks good :+1:

**Comment by jancborchardt** [comment]
@libasys hello? :) Some parts of this are still relevant. Should I open a new pull request?

**Comment by libasys** [comment]
please wait i commit today version 1.0.5 with placement fixes popover, some google like time slider, and internalization time feature for our american friends!

**Comment by jancborchardt** [comment]
@libasys ok, it would be cool if you could keep your commits smaller. The last ones have been quite huge, and basically impossible for people to follow what has been added.

**Comment by jancborchardt** [comment]
Well, seems like there is no real activity anymore on this app, as previously feared. Moving CalDAV and CardDAV into core will alleviate the problem so that at least the sync will always work: https://github.com/owncloud/core/pull/20197 & https://github.com/owncloud/core/pull/20184

**Pull request closed without merging**
