### PR TITLE
fix icon, and it not showing in apps management

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @libasys @DeepDiver1975 @sahne123 @MorrisJobke @schiesbn @lukasreschke

Same for the pull request to Contacts+ https://github.com/libasys/contactsplus/pull/15

### CODE REVIEW

**Comment by Bullnados** [comment]
Looks like the "normal" icon for calendar. If u have installed both u cant distinguish both if u have installd irect menu. So we decide to make a new one.

**Comment by jancborchardt** [comment]
We plan to move to Calendar+ as the default calendar for 8.2. Besides, they are distinguished by the app name. Also having two calendar apps enabled is nonsense, also because they do not use the same data.

**Comment by jancborchardt** [comment]
Also the current icon uses the outdated style with a dark »shadow« below it.

**Comment by sahne123** [comment]
@jancborchardt i am using both calendar apps because there is a dependencie of calendar in tasks wich i prefer to tasks plus. Thats why i seperated calendars and tasks.

Really appreciate to hear there are plans to use calendar+ as default.  In the long term two apps are no good way. If this will really happen we have to find a solution for tasks as well.

**Comment by jancborchardt** [comment]
@sahne123 cool! :) Yeah, we want to make sure we focus efforts on one app of each for Contacts, Calendar, Tasks.

For Contacts and Calendar we plan to go with @libasys' apps.

For Tasks though the already existing [Tasks app](https://github.com/owncloud/tasks) is very actively maintained by @raimund-schluessler and @Henni and already uses the main ownCloud style so we will definitely continue with that. @sahne123 as you also say, that’s preferred to Tasks+. So @libasys would be cool if we collaborate on one thing here too. :)

**Comment by jancborchardt** [comment]
@sahne123 btw, you are very welcome in our IRC channels #owncloud-calendar, #owncloud-contacts and #owncloud-dev in general. :)

**Comment by raimund-schluessler** [comment]
@jancborchardt Calendar+ will become the new default calendar for owncloud? Was that announced anywhere already and what will happen to the "old" calendar app (and especially to the rework branch)? What are the reasons to switch to this app here instead of bundling the effort on the old calendar rework branch to implement the missing features?

Regarding [Tasks](https://github.com/owncloud/tasks) we will have problems with switching to calendar+ as it depends on the current default calendar app. I already started to resolve those problems by implementing own functions which replace the calendar libraries in https://github.com/owncloud/tasks/pull/228 but this will take some time. After this is done we would only have to adapt the database scheme for moving to calendar+. Anyway, the ideal solution would be moving the Cal/CardDAV stuff into core so that there is really no inter-app dependency left.

PS: We maybe should open new issues for discussing this to not spam this PR here ;)

**Comment by jancborchardt** [comment]
@raimund-schluessler it wasnt announced so far since it's still not decided and has only been talked about with the maintainers of the involved apps. We do want to focus on one thing, but the question is if it's Calendar+ or a rework branch (which is unfinished and written with AngularJS – quite a barrier to entry).

cc @DeepDiver1975 sooner or later we need to wrap up the email discussion, come to a decision and announce it so we can move forward.

**Comment by jancborchardt** [comment]
@libasys can you merge this please? We want to mark the Calendar+ app as approved in the apps management, but currently no app icon is shown so it doesn’t look very well.

**Comment by phsc84** [comment]
@libasys Is there a specific reason, why you are hesitating to accept this pull request?

**Comment by libasys** [comment]
can be closed i added complete new icons and rename the files! thanks for your help!

**Comment by jancborchardt** [comment]
Same as I said in the Contacts pull request https://github.com/libasys/contactsplus/pull/15#issuecomment-140453760:

> The app icon you did uses color, unlike any other app icon. Yes, we don’t have any guidelines for that published but app icons should be fully white as to not grab unneeded attention.
> 
> @libasys again, this is quite an opaque development process you do with your apps. I want to help, and here I am with a very simple pull request not tended to for 2 months. And then subsequently closed. Exactly the complaints you had with the current Calendar app …
> 
> I can’t stress it enough: We need to work together here in an open process. Otherwise our Contacts and Calendar apps will never have proper quality.

**Pull request closed without merging**
